# netlify.toml
[build]
  # Directory to publish (build output)
  publish = "build"

  # Command to build your site
  command = "npm run build"

  # Node.js version to use (optional, Netlify will use the latest LTS by default)
  # node = "14.15.1"

[[redirects]]
  # Redirects all requests to the main index.html (for React Router)
  from = "/*"
  to = "/index.html"
  status = 200
